[package]
name = "cpp-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
clang-ast = "0.1.22"
color-eyre = "0.6.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
syn = "2.0.55"
quote = "1.0.35"
proc-macro2 = "1.0.79"
